### ISSUE TITLE
Paid version still shows Free Trial in the CMS

### ISSUE THREAD

**Issue by bruno-canada** [AcclaroInc/craft-translations#437]
We have purchased the Translations license and updated the license key; however, it still shows as Free Trial in the CMS. What are we missing?

Project config relevant part:
```
  translations:
    edition: standard
    enabled: true
    licenseKey: AU7E******
``` 

System settings:
Craft CMS v3.8.9
Translations v2.2.4
PHP v8.0.24
DB: MySQL v8.0.23
